<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<form method="POST">
    <br>
    <table>
        <tr>
            <td><label>Withdrawal Amount</label></td>
            <td><label>
                    <input name="withdrawalAmount" placeholder="Enter Amount" required>
                </label></td>
        </tr>
        <tr>
            <td><label>Select Account</label></td>
            <td><select>
                    <option value="savings">Savings Account</option>
                    <option value="cheque">Cheque Account</option>
                    <option value="fastsaver">FastSaver Account</option>
                </select></td>
        </tr>
        <tr>
            <td></td>
            <td><button name="withdraw" type="submit" class="btn btn-default" value="submit">Withdraw</button></td>
        </tr>
    </table>
</form>
<a href=<?= $linkTo('transactionIndex'); ?>>Transaction List</a>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
