<?php include "header.phtml" ?>
<!---------- Body starts --------------->
    <form method="POST">
        <table>
            <tr>
                <td><label>Account Type</label></td>
                <td><select name="accountType">
                        <option value="Savings">Savings</option>
                        <option value="Cheque">Cheque</option>
                        <option value="CreditCard">CreditCard</option>
                    </select></td>
            </tr>
            <tr>
                <td></td>
                <td><button name="create" type="submit" class="btn btn-default" value="submit">Create</button></td>
            </tr>
        </table>
    </form>

<br>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>