<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<form method="POST">
    <br>
    <table>
        <tr>
            <td><label>Deposit Amount</label></td>
            <td><label>
                    <input name="depositAmount" placeholder="Enter Amount" required>
                </label></td>
        </tr>
        <tr>
            <td><label>Select Account</label></td>
            <td><select>
                    <option value="savings">Savings Account</option>
                    <option value="cheque">Cheque Account</option>
                    <option value="fastsaver">FastSaver Account</option>
                </select></td>
        </tr>
        <tr>
            <td></td>
            <td><button name="deposit" type="submit" class="btn btn-default" value="submit" onclick="href= <?= $linkTo('accountDeposited', ['id' => $account->getId()]);?>">Deposit</button></td>
        </tr>
    </table>
</form>

<a href=<?= $linkTo('transactionIndex'); ?>>Transaction List</a>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
