<?php include "header.phtml" ?>
<!---------- Body starts --------------->
    <form method="POST">
        <table>
            <tr>
                <td><label>Account Type</label></td>
                <td><label>
                        <input name="accountType" placeholder="Enter Type" required>
                    </label></td>
            </tr>
            <tr>
                <td><label>User ID</label></td>
                <td><label>
                        <input name="userID" placeholder="Enter User ID"  required>
                    </label></td>
            </tr>
            <tr>
                <td></td>
                <td><button name="create" type="submit" class="btn btn-default" value="submit">Create</button></td>
            </tr>
        </table>
    </form>

<br>
    <!---------- Body ends -------------------->
<?php include "footer.phtml" ?>