<?php include "header.phtml" ?>
<!---------- Body starts --------------->

<br>
<table>
    <tr>
        <th>Account ID</th>
        <th>Account Name</th>
    </tr>
    <?php foreach ($accounts as $account) { ?>
    <tr>
        <td><?= $account->getId() ?></td>
        <td><?= $account->getName() ?></td>
        <td><a href= <?= $linkTo('accountDelete', ['id' => $account->getId()]);?> >delete</a></td>
    </tr>
    <?php } ?>
</table>

<a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>