<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<form method="POST">
    <table>
        <tr>
            <td><label>Deposit Amount</label></td>
            <td><label>
                    <input name="depositAmount" placeholder="Enter Amount" required>
                </label></td>
        </tr>
        <tr>
            <td><label>Select Account</label></td>
            <td><label>
                    <input name="accountID" placeholder="Enter Account ID"  required>
                </label></td>
        </tr>
        <tr>
            <td></td>
            <td><button name="deposit" type="submit" class="btn btn-default" value="submit">Create</button></td>
        </tr>
    </table>
</form>

<a href=<?= $linkTo('accountIndex'); ?>>Back</a>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
