<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KTC Banking</title>
    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
</head>
<body>
<header>
    <h1>KTC BANKING</h1>
    <div class="header-right">
        <?php
            session_start();
            if (isset($_SESSION['userName'])) {
                $userName = $_SESSION['userName'];
                echo "<p>Welcome $userName</p>";
            }
        ?>
        <a href=<?= $linkTo('Home'); ?>>Home</a>
        <?php
            if (isset($_SESSION['userName'])) {
                if ($_SESSION['userName'] == "admin") {
                    $href = $linkTo('userIndex');
                    echo "<a href=$href>Users</a>";
                }
                $href = $linkTo('userLogout');
                echo "<a href=$href>Log out</a>";
                $href = $linkTo('accountIndex');
                echo "<a href=$href>Accounts</a>";
                $href = $linkTo('transactionIndex');
                echo "<a href=$href>Transactions</a>";
                $href = $linkTo('accountCreate');
                echo "<a href=$href>Create account</a>";
            }
        ?>
        <!--<a href=<?= $linkTo('Home'); ?>>Home</a>
        <a href=<?= $linkTo('userIndex'); ?>>Users</a>
        <a href=<?= $linkTo('transactionIndex'); ?>>Transactions</a>
        <a href=<?= $linkTo('accountWithdraw'); ?>>Withdraw</a>
        <a href=<?= $linkTo('accountDeposit'); ?>>Deposit</a>
        <a href=<?= $linkTo('accountCreate'); ?>>Create account</a>
        <a href="mailto:ktc@ktc.com">Email Us</a>-->
    </div>
</header>
<!---------- Header ends --------------->