<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KTC Banking</title>
    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
</head>
<body>
<header>
    <h1>KTC BANKING</h1>
    <div class="header-right">
        <a href=<?= $linkTo('accountIndex'); ?>>Home</a>
        <a href="about.html">About</a>
        <a href="mailto:ktc@ktc.com">Email Us</a>
    </div>
</header>
<!---------- Header ends --------------->