<?php include "header.phtml" ?>
<!---------- Body starts --------------->

<br>
<table>
    <tr>
        <th>User ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Password</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Dob</th>
    </tr>
    <?php foreach ($users as $user) { ?>
        <tr>
            <td><?= $user->getId() ?></td>
            <td><?= $user->getFirstName() ?></td>
            <td><?= $user->getLastName() ?></td>
            <td><?= $user->getPassword() ?></td>
            <td><?= $user->getEmail() ?></td>
            <td><?= $user->getPhone() ?></td>
            <td><?= $user->getDateOfBirth() ?></td>
        </tr>
    <?php } ?>
</table>


<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>
